mqtt:
  image: toke/mosquitto
  container_name: mqtt
  ports:
    - "1883:1883"
    - "9001:9001"
  volumes:
    - ~/srv/mqtt/config:/mqtt/config:ro
    - ~/srv/mqtt/log:/mqtt/log/
    - ~/srv/mqtt/data:/mqtt/data/

influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
  volumes:
    - ~/srv/influxdb/data:/var/lib/influxdb

telegraf:
  image: telegraf:latest
  container_name: telegraf
  volumes:
    - ~/srv/telegraf/:/etc/telegraf:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  volumes:
    - ~/srv/grafana/data:/var/lib/grafana

